org: dbkompare
app: db-kompare
service: db-kompare-resources
configValidationMode: error

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-west-1
  stage: ${opt:stage, 'dev'}

resources:
  Resources:
    Databases:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: db-kompare-databases-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    Metrices:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: db-kompare-metrices-${self:provider.stage}
        AttributeDefinitions:
          - AttributeName: database_id
            AttributeType: S
          - AttributeName: date
            AttributeType: S
        KeySchema:
          - AttributeName: database_id
            KeyType: HASH
          - AttributeName: date
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
